version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Thiru2003@
      MYSQL_DATABASE: online_shopping
    ports:
      - "3306:3306"
    networks:
      - online-shopping-network

networks:
  online-shopping-network:
    driver: bridge
