server:
  port: 8081
spring:
  application:
    name: product-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshopping
    username: Thiru
    password: Thiru2003@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # Connection pool settings (optional)
      
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'none' for production
    show-sql: true  # Enable logging of SQL queries (optional)
    properties:
      hibernate:
        format_sql: true
